# --- USER INPUT PARAMETERS
# Parameters below can be writen with none, single or double quotes.
#   --- I/O parameters
coordinates: model.pdb
# LIBRARY of ligands
cif_library: input/ligands.cif
output: output/

#   --- Subroutine to process resampled streams
process_script: process.sh

#   --- Crystal parameters
cell: 62.5 62.5 112  90  90 120
space_group: P63    
point_group: 6/m

#   --- RESAMPLING parameters
# Options: 'Bootstrap', 'Jackknife', or 'Halves'
method: 'Bootstrap' 
samples: 100
sample_start: 0

#   --- POLDER analysis
# selection: 'chain a and (resid 400 or resid 401)'

#   --------------------------------------------------------------------------
#   --- OPTIONAL PARAMETERS
# # Find all input files from directory
# input: input/

# # For creating datasets of same size
# fixed_size: 10_000

# # Only for 'Jackknife'
# threshold: 0.8
